# Generated by Django 4.1.3 on 2022-12-13 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('subheader', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 18, 8, 21, 496502))),
                ('date_last_updated', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 18, 8, 21, 496512))),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('dateSubscribed', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'db_table': 'subscriber',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('E', 'Engaged'), ('R', 'In a relationship'), ('O', 'Other')], max_length=20, null=True)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('subscriber', models.ForeignKey(blank=True, db_column='subscriber_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.subscriber')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.article')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.person')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiWebsite.person'),
        ),
    ]
