# Generated by Django 4.1.3 on 2022-11-18 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('subheader', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBecameAuthor', models.DateField(default=datetime.datetime.today)),
                ('about', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSubscribed', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('E', 'Engaged'), ('R', 'In a relationship'), ('O', 'Other')], max_length=20, null=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.author')),
                ('subscriber', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraphText', models.TextField()),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.article')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiWebsite.person')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='wikiWebsite.person'),
        ),
    ]
