# Generated by Django 4.1.3 on 2022-12-13 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 18, 41, 19, 441015)),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 18, 41, 19, 441025)),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
