# Generated by Django 4.1.3 on 2022-12-11 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wikiWebsite",
            "0002_rename_authors_article_author_alter_article_header_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 4, 49, 11, 544826)
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 4, 49, 11, 544849)
            ),
        ),
    ]
